<a href="https://colab.research.google.com/github/rohitkhadka1/AI-ML-DS/blob/main/Gradients_Jacobians_Hessians.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Jacobian

In [2]:
from torch.autograd.functional import jacobian
import torch

def func(x):
  return torch.stack([x[0] * x[1], x[0] + x[1]])

x = torch.tensor([1.0, 2,0], requires_grad = True)

# Compute Jacobian matrix
j = jacobian(func, x)
j

tensor([[2., 1., 0.],
        [1., 1., 0.]])

Gradient

In [4]:
weight = torch.tensor([4.0], requires_grad=True)
gradient = weight ** 2 + 2 * weight + 1

gradient.backward()

print(weight.grad)

tensor([10.])


Hessian

In [5]:
from torch.autograd.functional import hessian

def scalar_func(x):
  return x[0] ** 2 + 2 * x[0] * x[1] + x[1] ** 2

x = torch.tensor([1.0, 2.0], requires_grad= True)

hess_ian = hessian(scalar_func, x)
hess_ian

tensor([[2., 2.],
        [2., 2.]])